[[Libtool]]
arch = "aarch64"
git-tree-sha1 = "baa93e66746fb5f6adb32a4c4297c846b66e9f45"
os = "macos"

    [[Libtool.download]]
    sha256 = "ae9fbd7317e70c68299b8f34083e6e64f25ffdd62f6881b60e95e24220fdc3ba"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+4/Libtool.v2.4.7.aarch64-apple-darwin.tar.gz"
[[Libtool]]
arch = "aarch64"
git-tree-sha1 = "a5c4d34d28f9e433cb316550931deb51246a0d3c"
libc = "glibc"
os = "linux"

    [[Libtool.download]]
    sha256 = "19c1c6140f401fce0d501f9401641340a80e4d000d8194066b1f17d84f99da39"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+4/Libtool.v2.4.7.aarch64-linux-gnu.tar.gz"
[[Libtool]]
arch = "aarch64"
git-tree-sha1 = "f31dd6b8d2f6b47a78558753923a58dd70363e0f"
libc = "musl"
os = "linux"

    [[Libtool.download]]
    sha256 = "0dbaa24063ba781d60cf79492c089bc96774f37702772e810d183fdf32d76b7d"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+4/Libtool.v2.4.7.aarch64-linux-musl.tar.gz"
[[Libtool]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "97dac79cc862532bcde254246b73b0371524dea6"
libc = "glibc"
os = "linux"

    [[Libtool.download]]
    sha256 = "789c00676904b68e4a86dca6130b3af38485adb8222b16148364d2260df7a2bc"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+4/Libtool.v2.4.7.armv6l-linux-gnueabihf.tar.gz"
[[Libtool]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "41f46a37099e572e550441c0afc5bab737338ed5"
libc = "musl"
os = "linux"

    [[Libtool.download]]
    sha256 = "0005145de68a59361742be4112207cc314ba7f1f0981899a5bb0d84c11e27334"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+4/Libtool.v2.4.7.armv6l-linux-musleabihf.tar.gz"
[[Libtool]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4bee47df68693eea8b21c46cb0c428728dc7d040"
libc = "glibc"
os = "linux"

    [[Libtool.download]]
    sha256 = "e13f8eb4b4e383c146d806b7ae02c783e22cf7cd40a84cc64c527da822cf28c5"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+4/Libtool.v2.4.7.armv7l-linux-gnueabihf.tar.gz"
[[Libtool]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9ad94c05363f224f40c5904dd2f14932d876aeee"
libc = "musl"
os = "linux"

    [[Libtool.download]]
    sha256 = "1e6eb47018777e3897770924767ca9da9bfbae5dbf631e000b94dcd1eec8d36a"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+4/Libtool.v2.4.7.armv7l-linux-musleabihf.tar.gz"
[[Libtool]]
arch = "i686"
git-tree-sha1 = "fd6161395f68695e84d0fe7bec52b4e317a21bea"
libc = "glibc"
os = "linux"

    [[Libtool.download]]
    sha256 = "5301a6cf697e74cf7e8291403738bc0ce65a697cfd35501964eab38f365f5de8"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+4/Libtool.v2.4.7.i686-linux-gnu.tar.gz"
[[Libtool]]
arch = "i686"
git-tree-sha1 = "89766443411d945ed696be0f77d1d611eac2c812"
libc = "musl"
os = "linux"

    [[Libtool.download]]
    sha256 = "fce5a9040cb3249fc1e49609a8be2124b7220b055a909071e7d62a7e4bea8134"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+4/Libtool.v2.4.7.i686-linux-musl.tar.gz"
[[Libtool]]
arch = "i686"
git-tree-sha1 = "6058debaade3306100a771b03b05f39d53de87b2"
os = "windows"

    [[Libtool.download]]
    sha256 = "5c54587f4cacce1de9401bd1b60e7f479cf2ec2204d519877d152f83d0fdd113"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+4/Libtool.v2.4.7.i686-w64-mingw32.tar.gz"
[[Libtool]]
arch = "powerpc64le"
git-tree-sha1 = "306313c57d0945ad0da441f89efed6e335123db6"
libc = "glibc"
os = "linux"

    [[Libtool.download]]
    sha256 = "23b78ab5640d737b0d9bdc296dd00070f86d467ecad2824572d054650ba6f35d"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+4/Libtool.v2.4.7.powerpc64le-linux-gnu.tar.gz"
[[Libtool]]
arch = "x86_64"
git-tree-sha1 = "143149d1d8410ded9bf8c4027e8dd9c59e000fd7"
os = "macos"

    [[Libtool.download]]
    sha256 = "6b2ded73b661c419de11ee3a10d490b5bf696aef778e4abd3eb0219572d8fbd0"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+4/Libtool.v2.4.7.x86_64-apple-darwin.tar.gz"
[[Libtool]]
arch = "x86_64"
git-tree-sha1 = "f84f9fc5322a791ec88feb35ee78a8857ffe3199"
libc = "glibc"
os = "linux"

    [[Libtool.download]]
    sha256 = "66ab4ca91b413c64eee943a5c2d166b5c5616706aa281b17b8bb6c18478fd9be"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+4/Libtool.v2.4.7.x86_64-linux-gnu.tar.gz"
[[Libtool]]
arch = "x86_64"
git-tree-sha1 = "aa02e20f18a07c9135187606b7fe0c3464123bd3"
libc = "musl"
os = "linux"

    [[Libtool.download]]
    sha256 = "9a31024123277a9d2b172068189b5446dfbef1c6c9f6a80218fdf4744749c921"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+4/Libtool.v2.4.7.x86_64-linux-musl.tar.gz"
[[Libtool]]
arch = "x86_64"
git-tree-sha1 = "001058d87db39eb00a4e2c4dd7caa4794662bafa"
os = "freebsd"

    [[Libtool.download]]
    sha256 = "c2ef725680098edd1c26bb4d816275481f2d20a9cdcc99bc3eb24ad4efdb9f03"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+4/Libtool.v2.4.7.x86_64-unknown-freebsd.tar.gz"
[[Libtool]]
arch = "x86_64"
git-tree-sha1 = "a9f785b03b8040c6a3cd0dcc2b5d5260a345db2a"
os = "windows"

    [[Libtool.download]]
    sha256 = "86e2e3627125f344ed68b4b5c53bd346f27f7430ecb8016c4da9718bb81cdb7a"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+4/Libtool.v2.4.7.x86_64-w64-mingw32.tar.gz"
