[[Libtool]]
arch = "aarch64"
git-tree-sha1 = "8918249226e627ddf2dec7d72da8e6808af574c5"
os = "macos"

    [[Libtool.download]]
    sha256 = "f21da3b5efe80b9e58298f9f883ef0cf8890c963a7397b55c06c73420bf93341"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+0/Libtool.v2.4.7.aarch64-apple-darwin.tar.gz"
[[Libtool]]
arch = "aarch64"
git-tree-sha1 = "061e217024c19a447bb951d4934a09e67f1e9e61"
libc = "glibc"
os = "linux"

    [[Libtool.download]]
    sha256 = "8c0160aa80fe6922fb9f6947dd23a7bff9704f292ac4b943d7417e0938a9f839"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+0/Libtool.v2.4.7.aarch64-linux-gnu.tar.gz"
[[Libtool]]
arch = "aarch64"
git-tree-sha1 = "69e96f29817a18e9b2c8cded5ff1a774dca81771"
libc = "musl"
os = "linux"

    [[Libtool.download]]
    sha256 = "a444f855c0640b2b8a41b99134ef18c9fbf8bedb6386c9224a1e7f25a84877de"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+0/Libtool.v2.4.7.aarch64-linux-musl.tar.gz"
[[Libtool]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1eb576ef42ecfc09a8bf7363046162e0a6d21442"
libc = "glibc"
os = "linux"

    [[Libtool.download]]
    sha256 = "2bda106f382ae965f699c22e6775de92c71d3153acf4ff0696ef12a562940b41"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+0/Libtool.v2.4.7.armv6l-linux-gnueabihf.tar.gz"
[[Libtool]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "dffd5cad12fe9538929bf3edd276764a4a800171"
libc = "musl"
os = "linux"

    [[Libtool.download]]
    sha256 = "a0863f48017bb59df29b64b80659ae2ef7a6f8741f862115618509557c1ff46a"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+0/Libtool.v2.4.7.armv6l-linux-musleabihf.tar.gz"
[[Libtool]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "92c7f8e7efc8b036b3c3d584fea5d9a1d34f7897"
libc = "glibc"
os = "linux"

    [[Libtool.download]]
    sha256 = "a5783e8dafc368ca593f35c918b1b5b9fb7db301004e69efec8d1c39b01917d9"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+0/Libtool.v2.4.7.armv7l-linux-gnueabihf.tar.gz"
[[Libtool]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8c95ab3fd8854aecb29e48fb35754bed177f9b5d"
libc = "musl"
os = "linux"

    [[Libtool.download]]
    sha256 = "d5b3e145b746d88d17a4bb6adfda00df8f4f1cbc6eecdf74d782e2c235bfc4bc"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+0/Libtool.v2.4.7.armv7l-linux-musleabihf.tar.gz"
[[Libtool]]
arch = "i686"
git-tree-sha1 = "2bb7f703bfbf98d05770feb31c5be85f8352a515"
libc = "glibc"
os = "linux"

    [[Libtool.download]]
    sha256 = "c6bcf74bd0bab5ba6635c819fdcdcf21be5475ae98eb25eeedf54b0bb0eacb03"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+0/Libtool.v2.4.7.i686-linux-gnu.tar.gz"
[[Libtool]]
arch = "i686"
git-tree-sha1 = "9cebc3dbc085f6e77a47656ca0c01bef41a2cd4c"
libc = "musl"
os = "linux"

    [[Libtool.download]]
    sha256 = "d90dca5f078cc5b51432ae016f072bd0fa4164dc0c4e96382c2b384739abaf0b"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+0/Libtool.v2.4.7.i686-linux-musl.tar.gz"
[[Libtool]]
arch = "i686"
git-tree-sha1 = "4d90194a25977049f01ba827b9b7145ba56cea71"
os = "windows"

    [[Libtool.download]]
    sha256 = "bed0b6911f67eeea586a28fdb8fdaf85188a5fea58a20110d4816de9d4ec7659"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+0/Libtool.v2.4.7.i686-w64-mingw32.tar.gz"
[[Libtool]]
arch = "powerpc64le"
git-tree-sha1 = "d10ccdd17cc6c077442ab20ca8c68b43105b9172"
libc = "glibc"
os = "linux"

    [[Libtool.download]]
    sha256 = "aba5acb7ce05a9abd9f79290f2beacbd1c4ddcf4cf2938b0618c06dd9a59846d"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+0/Libtool.v2.4.7.powerpc64le-linux-gnu.tar.gz"
[[Libtool]]
arch = "x86_64"
git-tree-sha1 = "10de5a1a321e93de3ac8a34b62b7b424303d34f9"
os = "macos"

    [[Libtool.download]]
    sha256 = "85306d3a9ea084440764a0f3f816936d21f59c4daf689e547cdf24c0dcd44651"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+0/Libtool.v2.4.7.x86_64-apple-darwin.tar.gz"
[[Libtool]]
arch = "x86_64"
git-tree-sha1 = "49c231b3b06a7cd0e4881caaeddc07553194a709"
libc = "glibc"
os = "linux"

    [[Libtool.download]]
    sha256 = "cccc046446ca705cc5a622e5019db02218d6b28903f9a54cb65fc95d6376e029"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+0/Libtool.v2.4.7.x86_64-linux-gnu.tar.gz"
[[Libtool]]
arch = "x86_64"
git-tree-sha1 = "fd4e29ea6a7fec1767b7b79c9ea0ca5a34a11b22"
libc = "musl"
os = "linux"

    [[Libtool.download]]
    sha256 = "ec49474d46165206b56837b14abea12c27f93cc3f81ef7a75abc7c008b23a906"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+0/Libtool.v2.4.7.x86_64-linux-musl.tar.gz"
[[Libtool]]
arch = "x86_64"
git-tree-sha1 = "8271335466d25f5dc9d7308460a0c577f3139a32"
os = "freebsd"

    [[Libtool.download]]
    sha256 = "5dc1ad152ea6b6c5a96cafe8ca4f41b44132ffa139923c4da172fbf3e85fafdd"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+0/Libtool.v2.4.7.x86_64-unknown-freebsd.tar.gz"
[[Libtool]]
arch = "x86_64"
git-tree-sha1 = "77fa40fbfc629e53f97e5922e948dcdd599ae837"
os = "windows"

    [[Libtool.download]]
    sha256 = "b806736b422a8092a73b706c5a784513058d9bca681fcbc708ef04cfff0ef70e"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+0/Libtool.v2.4.7.x86_64-w64-mingw32.tar.gz"
