[[Libtool]]
arch = "aarch64"
git-tree-sha1 = "9aaf6572f8d304afb76c030b145fef8b54671c2d"
libc = "glibc"
os = "linux"

    [[Libtool.download]]
    sha256 = "e0ebae482940ee91ae9d2029dd275547ed04131f004803cf19e53e59fb86bd86"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.6+1/Libtool.v2.4.6.aarch64-linux-gnu.tar.gz"
[[Libtool]]
arch = "aarch64"
git-tree-sha1 = "d1753ca3acd57cde14b93e69e7808ee1481c6002"
libc = "musl"
os = "linux"

    [[Libtool.download]]
    sha256 = "f9fd4a4a8bb9c2999fb4337a851bfef149d08851fd3489503f31cc594ad17c8f"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.6+1/Libtool.v2.4.6.aarch64-linux-musl.tar.gz"
[[Libtool]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "173373d8ee4e2580641c5258037dda7eb0998027"
libc = "glibc"
os = "linux"

    [[Libtool.download]]
    sha256 = "167b248fa96d7f1cbf2d6a28408e501b5e2f56257366932b28cd9fb760cc3b6a"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.6+1/Libtool.v2.4.6.armv7l-linux-gnueabihf.tar.gz"
[[Libtool]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6e1b68fdeeea8c295b5d0cc8ce5142045d8487df"
libc = "musl"
os = "linux"

    [[Libtool.download]]
    sha256 = "7cb1640fce6f2a72c1cb8f31db04f3cfcc99c37fbeeda0553b66d46ab4ee38c6"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.6+1/Libtool.v2.4.6.armv7l-linux-musleabihf.tar.gz"
[[Libtool]]
arch = "i686"
git-tree-sha1 = "f9867234db17305bcb6e65b623a358a934e4ed9d"
libc = "glibc"
os = "linux"

    [[Libtool.download]]
    sha256 = "8e6a7c5bbd7a6e30722cb982007a80bf359d3232cf59c0a1e4e5dd2568f0158a"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.6+1/Libtool.v2.4.6.i686-linux-gnu.tar.gz"
[[Libtool]]
arch = "i686"
git-tree-sha1 = "355728a5df6756cbeff1292f9cf7151ebe04a5e4"
libc = "musl"
os = "linux"

    [[Libtool.download]]
    sha256 = "0eaa1003eccabea3f9a6798b8857962db3b7637ff693540456da4f1a56106a14"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.6+1/Libtool.v2.4.6.i686-linux-musl.tar.gz"
[[Libtool]]
arch = "i686"
git-tree-sha1 = "3feefd70ca46919eb9975585f44040e0f81954ea"
os = "windows"

    [[Libtool.download]]
    sha256 = "336d417ca6c973904a61529dca4513ebbac2390af836c41e8ebb48b754b8ecb4"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.6+1/Libtool.v2.4.6.i686-w64-mingw32.tar.gz"
[[Libtool]]
arch = "powerpc64le"
git-tree-sha1 = "d309f562036f40e9c1a50ae3781cb08c87c844dd"
libc = "glibc"
os = "linux"

    [[Libtool.download]]
    sha256 = "1ff39bd7d5ed9f183e1acfd365c8c75fe930f4ef47e8a28ca8aa82a4fd261211"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.6+1/Libtool.v2.4.6.powerpc64le-linux-gnu.tar.gz"
[[Libtool]]
arch = "x86_64"
git-tree-sha1 = "b61a745d66d9e1d87bdf1cd5de22f0eef082c83a"
os = "macos"

    [[Libtool.download]]
    sha256 = "314c2c71ec64847c9f0f33d8c4d13f1fc9ec6bcf6b23a42ae023a58c6fbbaeb6"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.6+1/Libtool.v2.4.6.x86_64-apple-darwin.tar.gz"
[[Libtool]]
arch = "x86_64"
git-tree-sha1 = "6580da66b054ddf663dd5e62fda01b9c948e0aed"
libc = "glibc"
os = "linux"

    [[Libtool.download]]
    sha256 = "6dc8429fc31724b1d61a3340b8840e5d1f60fc60a032dcf1b6462f2549849611"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.6+1/Libtool.v2.4.6.x86_64-linux-gnu.tar.gz"
[[Libtool]]
arch = "x86_64"
git-tree-sha1 = "0dbba7a6fa449b5d4f426250335d096aba35833b"
libc = "musl"
os = "linux"

    [[Libtool.download]]
    sha256 = "85be24ee71e0cea2389126e621fdef4151501b241528bc3216923b949560f58b"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.6+1/Libtool.v2.4.6.x86_64-linux-musl.tar.gz"
[[Libtool]]
arch = "x86_64"
git-tree-sha1 = "fa7453459182daaf1ec66251c71698699850facd"
os = "freebsd"

    [[Libtool.download]]
    sha256 = "45f460cb702094d43feb689d7c34cdcee989ce73e65b2cbd8a55ab270fa9edbf"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.6+1/Libtool.v2.4.6.x86_64-unknown-freebsd.tar.gz"
[[Libtool]]
arch = "x86_64"
git-tree-sha1 = "38e3c1aafaee1e3f7a93675d41d0e67d711afa51"
os = "windows"

    [[Libtool.download]]
    sha256 = "8419087eb76e65ac3c66b27f0367e98559306e121e6ef9491f0b148961b35621"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.6+1/Libtool.v2.4.6.x86_64-w64-mingw32.tar.gz"
