[[Libtool]]
arch = "aarch64"
git-tree-sha1 = "93295b51db3e5d8275c4bd5054ad6421f0fd6d4e"
libc = "glibc"
os = "linux"

    [[Libtool.download]]
    sha256 = "bd7d10b57768e03fa3bae5cfad84b0e279d1b54ae20a33f43bede22b3eb5391a"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.6+0/Libtool.v2.4.6.aarch64-linux-gnu.tar.gz"
[[Libtool]]
arch = "aarch64"
git-tree-sha1 = "83b53aab367fdb467df3c7ac2d406567178541b4"
libc = "musl"
os = "linux"

    [[Libtool.download]]
    sha256 = "f6a3fbf3fcfe0bf12d59b94923f1bb3daa367fe2c3eb87f49add0b7fe06a7a74"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.6+0/Libtool.v2.4.6.aarch64-linux-musl.tar.gz"
[[Libtool]]
arch = "armv7l"
git-tree-sha1 = "858b1f15768910b4082b91c88993114a6c618bc8"
libc = "glibc"
os = "linux"

    [[Libtool.download]]
    sha256 = "742a9a4421102f146245ce70c7fe725885da192a5e14eba31f76aa9e755c0299"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.6+0/Libtool.v2.4.6.armv7l-linux-gnueabihf.tar.gz"
[[Libtool]]
arch = "armv7l"
git-tree-sha1 = "af57cf314557b890ffffdf49d26400f9894f1c30"
libc = "musl"
os = "linux"

    [[Libtool.download]]
    sha256 = "b805418118cbb5c83ccb76a0dd22db924365a59081ce94d8cf5702533cfd4325"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.6+0/Libtool.v2.4.6.armv7l-linux-musleabihf.tar.gz"
[[Libtool]]
arch = "i686"
git-tree-sha1 = "7b57c97b5b6014e93fd41b17ba3a854cd67f30c0"
libc = "glibc"
os = "linux"

    [[Libtool.download]]
    sha256 = "072c81b2650fd5ae5591fc33328eaa400dcd22bc981d0f6ea4daeec5ae2d96b1"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.6+0/Libtool.v2.4.6.i686-linux-gnu.tar.gz"
[[Libtool]]
arch = "i686"
git-tree-sha1 = "9e3c657f031aa4826823a652651758b019d098fe"
libc = "musl"
os = "linux"

    [[Libtool.download]]
    sha256 = "59584d210b15378a50482f08e4639a47c16be4cc3ff67327be5f397d1c153d63"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.6+0/Libtool.v2.4.6.i686-linux-musl.tar.gz"
[[Libtool]]
arch = "i686"
git-tree-sha1 = "88bb1bdfda53b184bad79696288fec11d70ba0e5"
os = "windows"

    [[Libtool.download]]
    sha256 = "4c14d8b4781cb3dd7314a61c1b578d0bafc55eec1ca5edac6f424239ba86c9a1"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.6+0/Libtool.v2.4.6.i686-w64-mingw32.tar.gz"
[[Libtool]]
arch = "powerpc64le"
git-tree-sha1 = "740d79608197dfafd46b4f3bd93c52d3f8341991"
libc = "glibc"
os = "linux"

    [[Libtool.download]]
    sha256 = "29c9d9fecce12feea64d0fada359703975955a04aec7f7013dddc8a363a8c37f"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.6+0/Libtool.v2.4.6.powerpc64le-linux-gnu.tar.gz"
[[Libtool]]
arch = "x86_64"
git-tree-sha1 = "da69da4dfd7e490371326a6b74f837367bc5917b"
os = "macos"

    [[Libtool.download]]
    sha256 = "6e98874e7c6352bc7bb3e03f4a6f67200fa5f4ade77bac015f5bcce93f3a12dc"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.6+0/Libtool.v2.4.6.x86_64-apple-darwin14.tar.gz"
[[Libtool]]
arch = "x86_64"
git-tree-sha1 = "622ac0734aa9af2338cbd85ad1f53d53a56c9409"
libc = "glibc"
os = "linux"

    [[Libtool.download]]
    sha256 = "41205f8bf29047e0b99a1dc02cb25b6faf5bbefce4428e09ad4a4e05fb8bf537"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.6+0/Libtool.v2.4.6.x86_64-linux-gnu.tar.gz"
[[Libtool]]
arch = "x86_64"
git-tree-sha1 = "e837e82a41919f93ed4779d4e566f7a437fdaa19"
libc = "musl"
os = "linux"

    [[Libtool.download]]
    sha256 = "dd9d0a1df3cc4d33b5b70a6cb5c4fb90748382dbaeb2f3bebd1862d0e3ed0868"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.6+0/Libtool.v2.4.6.x86_64-linux-musl.tar.gz"
[[Libtool]]
arch = "x86_64"
git-tree-sha1 = "869f003ce246bed503cf37a7d484f69c2444256e"
os = "freebsd"

    [[Libtool.download]]
    sha256 = "6ec78d58d3a04a3935d0bac7b263b0e36306397216396c3def4e4bbbb1bddb7c"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.6+0/Libtool.v2.4.6.x86_64-unknown-freebsd11.1.tar.gz"
[[Libtool]]
arch = "x86_64"
git-tree-sha1 = "1bace9618b9b095811f82eb4bf0200183dfa23c8"
os = "windows"

    [[Libtool.download]]
    sha256 = "5cb426223d6096154a281679998423c342e36fad6754b2685d31deae64b64831"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.6+0/Libtool.v2.4.6.x86_64-w64-mingw32.tar.gz"
