[[Libtool]]
arch = "aarch64"
git-tree-sha1 = "fba589a2ac3d5bb328a94bbc8fb6bcb4ca9d24e1"
os = "macos"

    [[Libtool.download]]
    sha256 = "3ed2bc0cb8c5e2034136ace242e68960137415269da5c62dbb1616830ce7eb68"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+2/Libtool.v2.4.7.aarch64-apple-darwin.tar.gz"
[[Libtool]]
arch = "aarch64"
git-tree-sha1 = "8dd05ed1b7f5498abac79ef0bd15e936fc718037"
libc = "glibc"
os = "linux"

    [[Libtool.download]]
    sha256 = "afcfc4fd90e2d9369e65f1d900e1a438182cd131cb4605748a15e8ee3b173d64"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+2/Libtool.v2.4.7.aarch64-linux-gnu.tar.gz"
[[Libtool]]
arch = "aarch64"
git-tree-sha1 = "df848be1f9a8d588ef605a09cabee8c171a914ef"
libc = "musl"
os = "linux"

    [[Libtool.download]]
    sha256 = "629fb2de28e6cccfb3af74af6e988539cfeef5484ba924dc774f72c97a97428a"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+2/Libtool.v2.4.7.aarch64-linux-musl.tar.gz"
[[Libtool]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "34f2cc512a6162a7a9d659428576f0e2dd15ce29"
libc = "glibc"
os = "linux"

    [[Libtool.download]]
    sha256 = "cbe418768dd51557b6c28a02af7de1e3db47ffb66bf41ed6dc24fd1fdd85c750"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+2/Libtool.v2.4.7.armv6l-linux-gnueabihf.tar.gz"
[[Libtool]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7d9c5e69ca36eb62fad38e09b51feee2b841e0bb"
libc = "musl"
os = "linux"

    [[Libtool.download]]
    sha256 = "14293c50dfcd843241f0ba2cc4ba717a09bf1cee9fbe4e8ef4a97f1efcc298db"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+2/Libtool.v2.4.7.armv6l-linux-musleabihf.tar.gz"
[[Libtool]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d77f3853e1dce090258de32215e492d146fdde81"
libc = "glibc"
os = "linux"

    [[Libtool.download]]
    sha256 = "406ba2a7b4e7ea0bd77b71495885ca0f931c8cc81b7cd5572068d5881c6246e4"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+2/Libtool.v2.4.7.armv7l-linux-gnueabihf.tar.gz"
[[Libtool]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3b23020fe3f595c1409be90308744d3e4b9e670e"
libc = "musl"
os = "linux"

    [[Libtool.download]]
    sha256 = "e8b8625582c87a278513b4d24e9ab8448b2a8b43f3d48190b8eb89037d186d05"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+2/Libtool.v2.4.7.armv7l-linux-musleabihf.tar.gz"
[[Libtool]]
arch = "i686"
git-tree-sha1 = "0749bcc37bbfdd33bf24f91fc56b4eff7181be21"
libc = "glibc"
os = "linux"

    [[Libtool.download]]
    sha256 = "e9992525eb3b2ba3bcb34e83674766a83b9d53e8b140c7428cdf19296987334e"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+2/Libtool.v2.4.7.i686-linux-gnu.tar.gz"
[[Libtool]]
arch = "i686"
git-tree-sha1 = "01d8ae5974e92762b99f497fcb48890775b77ce4"
libc = "musl"
os = "linux"

    [[Libtool.download]]
    sha256 = "7284ca2fff5e49aa057a9eb268561aa8191f0045a9d62e754ea13a1118e3acac"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+2/Libtool.v2.4.7.i686-linux-musl.tar.gz"
[[Libtool]]
arch = "i686"
git-tree-sha1 = "ea23fccae1a093ca3862426a984802082cc17695"
os = "windows"

    [[Libtool.download]]
    sha256 = "9550f09c8ebff3c0835178bb3e607f135ee83b2beece8e518e2b5aaa782b6bdc"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+2/Libtool.v2.4.7.i686-w64-mingw32.tar.gz"
[[Libtool]]
arch = "powerpc64le"
git-tree-sha1 = "3af76d0c04829ebb3547f000105a3ef27e0f4bb3"
libc = "glibc"
os = "linux"

    [[Libtool.download]]
    sha256 = "adbc20c9d7b93ed52384cfe74df4f16949e1d22979b7f02b7dfb17dc13344690"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+2/Libtool.v2.4.7.powerpc64le-linux-gnu.tar.gz"
[[Libtool]]
arch = "x86_64"
git-tree-sha1 = "9fb1e7acf85641e24185d9f80cf405b1a262220b"
os = "macos"

    [[Libtool.download]]
    sha256 = "09a7a21298a87edd63c3ca697fc873faf2535ed7497c02afbd82efaf26632328"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+2/Libtool.v2.4.7.x86_64-apple-darwin.tar.gz"
[[Libtool]]
arch = "x86_64"
git-tree-sha1 = "a5358dd22f33e357ff6601ba8dd173d0e8c8faa6"
libc = "glibc"
os = "linux"

    [[Libtool.download]]
    sha256 = "78ac3ee42c0badcbc126f315a4be331469888ec746335f09061fd73b10b53d00"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+2/Libtool.v2.4.7.x86_64-linux-gnu.tar.gz"
[[Libtool]]
arch = "x86_64"
git-tree-sha1 = "2b638fb3e67fedf9fd286b9e4f6165795f46f896"
libc = "musl"
os = "linux"

    [[Libtool.download]]
    sha256 = "9f2d328a393dff31aa446aeb589d62669ab9ffbe89fd7550dfc5d13fe08133dd"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+2/Libtool.v2.4.7.x86_64-linux-musl.tar.gz"
[[Libtool]]
arch = "x86_64"
git-tree-sha1 = "51c676ca861e007282bd6be97d226dc5848e074e"
os = "freebsd"

    [[Libtool.download]]
    sha256 = "a19625b2b844ad67cdf31d39edfbebe0ab21f149f8196911a64e177a61672bc8"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+2/Libtool.v2.4.7.x86_64-unknown-freebsd.tar.gz"
[[Libtool]]
arch = "x86_64"
git-tree-sha1 = "e052468c4f9ef4e91e307469e486189481b3bf4e"
os = "windows"

    [[Libtool.download]]
    sha256 = "f6f77d70e872efe6531344f977617dd685f69190940c6be11def0ba79e694286"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+2/Libtool.v2.4.7.x86_64-w64-mingw32.tar.gz"
