[[Libtool]]
arch = "aarch64"
git-tree-sha1 = "7c85d2d06e044d9878314d65ac3ed7ebeaa0c638"
os = "macos"

    [[Libtool.download]]
    sha256 = "831c7196e80d10714be34fea8f9d7a961ab8073824230a4ac1bd94cbe5b10344"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+3/Libtool.v2.4.7.aarch64-apple-darwin.tar.gz"
[[Libtool]]
arch = "aarch64"
git-tree-sha1 = "247de3d065fd849366a46fb83a4652f346a884e1"
libc = "glibc"
os = "linux"

    [[Libtool.download]]
    sha256 = "a0ae3d27d9f89b9f5a3e174d02bf890e7452708ae2669004b9937a9b8eddbe89"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+3/Libtool.v2.4.7.aarch64-linux-gnu.tar.gz"
[[Libtool]]
arch = "aarch64"
git-tree-sha1 = "758d797b5b94aba6757a512ff56951ad900f4423"
libc = "musl"
os = "linux"

    [[Libtool.download]]
    sha256 = "06df9d2af0b467f7ad1a7a336d1c815769472f41e2a739ae633a8a4924be6a44"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+3/Libtool.v2.4.7.aarch64-linux-musl.tar.gz"
[[Libtool]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d70ab2a47a2351f058b8afbfdb9dd92cfc2a208e"
libc = "glibc"
os = "linux"

    [[Libtool.download]]
    sha256 = "e2623d521054c9c22c803a679420d0acc60a7fc4c02fd62342002846bab540dc"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+3/Libtool.v2.4.7.armv6l-linux-gnueabihf.tar.gz"
[[Libtool]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1d8329e2062e3fa58ae7b45d24ddc0e289fe3dfa"
libc = "musl"
os = "linux"

    [[Libtool.download]]
    sha256 = "eb8f4e95d711816c8b4a3753bb76e87ba92695f72ff9800780e7946e8b7563eb"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+3/Libtool.v2.4.7.armv6l-linux-musleabihf.tar.gz"
[[Libtool]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ca06bab452f9e9890aa071336796f092aa7bb31b"
libc = "glibc"
os = "linux"

    [[Libtool.download]]
    sha256 = "43745c9143e852e57c25232df5715de4b62f894d254f6b7281e79d812661c61b"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+3/Libtool.v2.4.7.armv7l-linux-gnueabihf.tar.gz"
[[Libtool]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "eef21e8baff81297f18841aa86f27636534aca40"
libc = "musl"
os = "linux"

    [[Libtool.download]]
    sha256 = "28525ab00e6766be45586f1d46e35afa6d3df41f1b1f9d4e6e7885a90195be87"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+3/Libtool.v2.4.7.armv7l-linux-musleabihf.tar.gz"
[[Libtool]]
arch = "i686"
git-tree-sha1 = "ee53d02f4eab29a2a875949c4be8f7703b4278d1"
libc = "glibc"
os = "linux"

    [[Libtool.download]]
    sha256 = "6d1eff695ad9107365174cadf8c0f40a3277bf5890f3fa69180cbc3496580457"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+3/Libtool.v2.4.7.i686-linux-gnu.tar.gz"
[[Libtool]]
arch = "i686"
git-tree-sha1 = "c9fa5a3c1c6826ec09380016b479d7fbb4a1cd62"
libc = "musl"
os = "linux"

    [[Libtool.download]]
    sha256 = "d850ea70d395a5d9e25c040ed4d9e6bdf27a126b553fd7796401ec6255c9cabe"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+3/Libtool.v2.4.7.i686-linux-musl.tar.gz"
[[Libtool]]
arch = "i686"
git-tree-sha1 = "0c1c565bde9ff5f691b6b4cf033895fc3db0e22e"
os = "windows"

    [[Libtool.download]]
    sha256 = "75fc51c85720ad7b85b3a567740bea0aa1c7b36094ddb0a4801451f68b8074b8"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+3/Libtool.v2.4.7.i686-w64-mingw32.tar.gz"
[[Libtool]]
arch = "powerpc64le"
git-tree-sha1 = "ad3cc437b4cc58c13703d9ed10a669dc2a1927aa"
libc = "glibc"
os = "linux"

    [[Libtool.download]]
    sha256 = "ddeb350652c0681422270720c101c679c9b997209dc8ee1086387c1dfba987f5"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+3/Libtool.v2.4.7.powerpc64le-linux-gnu.tar.gz"
[[Libtool]]
arch = "x86_64"
git-tree-sha1 = "893cafdaeec5957faf9b326cb72184b813ceb9b5"
os = "macos"

    [[Libtool.download]]
    sha256 = "a8c394c236b0f20c3032a030bfb0ea7d250f1b993dd09c29f1527d0b71046c94"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+3/Libtool.v2.4.7.x86_64-apple-darwin.tar.gz"
[[Libtool]]
arch = "x86_64"
git-tree-sha1 = "6aa884e1d28137e763e63d9bf23d5101c1a7e7a0"
libc = "glibc"
os = "linux"

    [[Libtool.download]]
    sha256 = "1c5b5635a1ecda0e5cf8a00f4ca63e9f80086f624173fa3e0e92068eae7d06f9"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+3/Libtool.v2.4.7.x86_64-linux-gnu.tar.gz"
[[Libtool]]
arch = "x86_64"
git-tree-sha1 = "6f7457ed715706bcacf214e3bf672bdfeefdd0ff"
libc = "musl"
os = "linux"

    [[Libtool.download]]
    sha256 = "71ce45bf07f9d795e105af136a0c952331272454a9a85423f8a8ca9a74d6793a"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+3/Libtool.v2.4.7.x86_64-linux-musl.tar.gz"
[[Libtool]]
arch = "x86_64"
git-tree-sha1 = "ded868375fb24bece1257f41d0b7e1f19de86ccd"
os = "freebsd"

    [[Libtool.download]]
    sha256 = "949eaf948ac042b5290f40521254737b7e2f6cb50a6a7bbb2f97b33e448d7f60"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+3/Libtool.v2.4.7.x86_64-unknown-freebsd.tar.gz"
[[Libtool]]
arch = "x86_64"
git-tree-sha1 = "c892947d656883365c6ba3e0af40e107ebe2989d"
os = "windows"

    [[Libtool.download]]
    sha256 = "b794df3eac3800de8fc52b952414ab5bd7b3d2eaf6231e80f020a114b649ab68"
    url = "https://github.com/JuliaBinaryWrappers/Libtool_jll.jl/releases/download/Libtool-v2.4.7+3/Libtool.v2.4.7.x86_64-w64-mingw32.tar.gz"
