# Autogenerated wrapper script for Libtool_jll for x86_64-w64-mingw32
export libltdl, libtool, libtoolize

JLLWrappers.@generate_wrapper_header("Libtool")
JLLWrappers.@declare_library_product(libltdl, "libltdl-7.dll")
JLLWrappers.@declare_file_product(libtool)
JLLWrappers.@declare_file_product(libtoolize)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libltdl,
        "bin\\libltdl-7.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_file_product(
        libtool,
        "bin\\libtool",
    )

    JLLWrappers.@init_file_product(
        libtoolize,
        "bin\\libtoolize",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
